#!/bin/bash
if ! which bashkit > /dev/null 2> /dev/null; then
	printf "send-text requires bashkit which is not installed...\n\n"
	curl -fs https://raw.github.com/mafintosh/bashkit/master/install | bash
	[ $? != 0 ] && exit 1
	printf "\n"
fi
BASHKIT_APP_INSTALL="bashkit install mafintosh/nexmo-send-text --bin send-text"
which send-text > /dev/null 2> /dev/null && BASHKIT_APP_INSTALL="bashkit update send-text"
[ ! -O "$(bashkit dirname)/bin" ] && BASHKIT_APP_INSTALL="sudo $BASHKIT_APP_INSTALL"
printf "\x1B[90m$BASHKIT_APP_INSTALL\x1B[39m\n"
$BASHKIT_APP_INSTALL --colors || exit 1
printf "\nsend-text is now installed\n"
